-- AlterTable
ALTER TABLE "household_survey" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "submitted_at" SET DATA TYPE TIMESTAMPTZ;
